- hosts: "{{ env }}"
  become: no
  tasks: 
    - name: remove any previous app services
      shell: | 
         if [ `docker service ls | grep -v NAME | grep mysvc | awk '{print $2}' | wc -l` -gt 0 ]; then  
            docker service rm `docker service ls | grep -v NAME | grep mysvc | awk '{print $2}'`
         else 
            echo "No Service found"
         fi
    - name: deploy app
      command: docker login -u suyashjain27 -p Azure@1010
      command: docker service create --name mysvc --replicas 2 -p 9080:8080 docker.io/suyashjain27/samplejavaapp:{{ build }}
